theme: jekyll-theme-cayman
title: SDG-OD
description: A Web application that links Open Data resources from multiple CKAN open platforms with the Sustainable Development Goals using Semantic Web Technologies.
